#██████╗░██████╗░░█████╗░░█████╗░██████╗░░█████╗░░█████╗░░██████╗████████╗░░░░░░░
#██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝╚══██╔══╝░░██╗░░
#██████╦╝██████╔╝██║░░██║███████║██║░░██║██║░░╚═╝███████║╚█████╗░░░░██║░░░██████╗
#██╔══██╗██╔══██╗██║░░██║██╔══██║██║░░██║██║░░██╗██╔══██║░╚═══██╗░░░██║░░░╚═██╔═╝
#██████╦╝██║░░██║╚█████╔╝██║░░██║██████╔╝╚█████╔╝██║░░██║██████╔╝░░░██║░░░░░╚═╝░░
#╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝╚═════╝░░╚════╝░╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░░░░░░░░

#The Prefix For The Broadcast
BroadcastPrefix: "&8&l[&c&lBroadcast&8&l]"

#Title Settings
#Timings are in ticks. [20 ticks = 1 second]
TitleFadeIn: 1
TitleDisplayTime: 20
TitleFadeOut: 1

Presets:
  example:
    message:
      - '&8&l&m========&3&lTest Server&8&l&m========'
      - '&8&l- &cLine 1'
      - '&8&l- #123456Line 2'
      - '&8&l- &9%player_name%'
      - '&8&l&m==========================='