main: Dev.ScalerGames.BroadcastPlus.Main
name: BroadcastPlus
version: 2.7.0
api-version: 1.13
author: ScalerGames
description: A Minecraft Broadcasting Plugin.
softdepend:
  - PlaceholderAPI
  - LuckPerms
  - HeadDatabase
loadbefore:
  - Essentials
commands:
  broadcast:
    aliases: [announce]
  broadcastplus:
    aliases: [bp]
  broadcastworld:
    aliases: [bw]
  localbroadcast:
    aliases: [lb]
  groupbroadcast:
    aliases: [gb]